dateModified: 1681829237
email:
  fromEmail: lewis@westmidlandsmedia.co.uk
  fromName: 'Digbeth Dining Club'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    011f13ac-1479-4bc4-9c8b-3b139b4f883a: 'Text Boxes' # Text Boxes
    40b37fc8-cefe-4aae-96a6-f1cd6413f072: Pages # Pages
    575aeb62-ff75-4973-9c15-386a4f6279a6: Common # Common
    898dfbc1-899e-42a3-9cd3-cbc2caa93565: 'Page Title' # Page Title
    8453ea1b-60dc-4ab6-8251-c2cf770fd031: Default # Default
    66776d11-ab86-4690-842c-b765c3af0cd2: 'Digbeth Dining Club' # Digbeth Dining Club
    aae96ca2-97c6-44c5-97a6-1de165ff9423: 'Digbeth Dining Club' # Digbeth Dining Club
    ac10df52-2161-4e70-b868-909862a59460: 'Page Info' # Page Info
    b97bede2-b444-45f8-b40c-4688ff98e9da: 'Lower Text' # Lower Text
    cc6ac803-ac8d-41af-b27a-67e17f377f26: 'Upper Text' # Upper Text
    d28e4460-91a3-4b26-a7ac-9c6f9a0d088b: Pages # Pages
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: 'Digbeth Dining Club'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
